name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  watch:
    types: [started]

jobs:
  run:
    name: Update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'

    - name: Execute
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: node main.js